### ISSUE TITLE
How about renaming `InnerServer` to `Storage`

### ISSUE THREAD

**Issue by Connor1996** [pingcap-incubator/tinykv#109]
`InnerServer` actually gives some operations on the underlying storage, maybe we can rename `InnerServer` and `DBReader` to a meaningful name, like `Storage` and `StorageReader`

**Comment by clark1013** [comment]
pick

**Comment by clark1013** [comment]
@Connor1996 Should we only rename the struct or the package `inner_server`? I have seen [tikv](https://github.com/tikv/tikv/tree/master/src/storage) project, They named the wrapped server `storage`. In my opinion, `Storage` is better, but `InnerServer` is also acceptable.

**Comment by Connor1996** [comment]
Rename all the related structs and packages. I'm okay with `InnerServer` too actually, what's your opinion? @nrc

**Comment by nrc** [comment]
I think renaming like this is a good idea. We should document exactly what `storage` means though because it is a little vague (better than `InnerServer` though.

**Comment by clark1013** [comment]
OK, I will do that later today.
