### ISSUE TITLE
TestRawNodeStart2C or TestRawNodeRestart2AC?

### ISSUE THREAD

**Issue by woodgear** [pingcap-incubator/tinykv#150]
master branch [TestRawNodeStart2C](https://github.com/pingcap-incubator/tinykv/blob/master/raft/rawnode_test.go#L187)
course branch [TestRawNodeRestart2AC](https://github.com/pingcap-incubator/tinykv/blob/course/raft/rawnode_test.go#L187)

**Comment by Connor1996** [comment]
should be `TestRawNodeRestart2AC`
