### ISSUE TITLE
Scope/requirements

### ISSUE THREAD

**Issue by nrc** [pingcap-incubator/tinykv#31]
I would like to define what is in and out of scope for the **initial iteration** of TinyKV. I'll start to make a list here, please comment if I got something wrong or if there are other things which should be in or out.

cc @siddontang, @Connor1996 

## In scope

- [x] Test framework
- [x] Distribution using Raft (Raft implemented as part of TinyKV, not using a library)
- [x] Raw and transactional API
- [x] Optimistic transactions (Percolator-style)
- [x] PD to balance regions and provide timestamps
- [x] Interoperable with TinySQL

## Out of scope

* Any kind of engine abstraction
* Debug or diagnostics services (for development only)
* Metrics/statistics
* Any GC
* Pessimistic transactions
* backup/restore; sst import
* profiler
* status server
* coprocessor
* batched commands
* security
* interoperable with real TiDB and real PD

**Comment by andylokandy** [comment]
I'm also involved in this project. From my limited information
- the coprocessor is definitely out of scope
- the Raft is also out of scope because we already have mit course  specifically for it
- the debug/error report system is reserved for development purpose. it may be removed eventually.
cc @Connor1996

**Comment by nrc** [comment]
> the Raft is also out of scope because we already have mit course specifically for it

what is the `raft` package for? Should it be removed or is that the MIT course implementation?

**Comment by Connor1996** [comment]
> * the Raft is also out of scope because we already have mit course  specifically for it

Raft is in the scope which @NingLin-P is working on

**Comment by Connor1996** [comment]
It should be
```
## In scope

* Test framework
* Distribution using Raft (Raft implemented as part of TinyKV, not using a library)
* Raw and transactional API
* Optimistic transactions (Percolator-style)
* Scheduler(cut from PD) to balance regions and provide timestamps 
* coprocessor (no need in this stage)

## Out of scope

* Any kind of engine abstraction
* Debug or diagnostics services (for development only)
* Metrics/statistics
* Any GC
* Pessimistic transactions
* backup/restore; sst import
* profiler
* status server
* batched commands
* security
* interoperable with real TiDB and TiKV
```
@nrc I do not quite understand what `snapshot server` indicate for

**Comment by nrc** [comment]
> interoperable with real TiDB and TiKV

It seems to me that this is fairly low cost to support and will make testing much easier (it would probably make this project more useful too, since we could compare more readily against real TiKV).

> snapshot server

The stuff that is in raftstore/store/snap.rs in TiKV. I don't know what it does! But it seems to be different from the Raft snapshots or the snapshots used in transactions and it runs as its own server, so I thought it might be separable.

> coprocessor (no need in this stage)

I'm just trying to list the work for the first iteration, I think we don't include the coprocessor in that and we might do it later?

**Comment by Connor1996** [comment]
> interoperable with real TiDB and TiKV

No, the RPC definition which contains a lot of performance optimization specific fields is too complicated to learn. One thing to note that the implementation will be deleted in the final. The students need to implement TinyKV themselves with tests and framework code provided(like MIT6.824). Our implementation will be moved to a private repo as a standard answer. 

Though TinyKV will interoperate with TinySQL(https://github.com/pingcap-incubator/tinysql), and that's why coprocessor need to be implemented later.

> snapshot server

I think you mean `server/snap.rs`? It's in the scope which is used to send raft snapshot between nodes. The corresponding code: `server/snap.rs` -> `tikv/inner_server/snap_runner.go`  and `raftstore/store/snap.rs` -> `tikv/raftstore/snap/snap.go`

> coprocessor (no need in this stage)

Yes

**Comment by nrc** [comment]
> One thing to note that the implementation will be deleted in the final. The students need to implement TinyKV themselves

OK, that makes sense, thanks.

> I think you mean server/snap.rs? 

I think server/snap.rs is the API, raftstore/store/snap.rs is the implementation. In any case, I think it is still part of Raft.

**Comment by nrc** [comment]
OK, I believe the requirements list (in the OP) is now complete and correct.

**Comment by nrc** [comment]
More things I'm unsure about given the code:

* txn heartbeat requests
* cleanup requests (Not sure if this counts as GC)
* MvccGetByKeyRequest and MvccGetByStartTsRequest

**Comment by nrc** [comment]
And here is part of the Context proto, I'm guessing we don't need to support these things, but not sure:

```
    CommandPri priority = 6;
    IsolationLevel isolation_level = 7;
    bool not_fill_cache = 8;
    bool sync_log = 9;
    bool handle_time = 10; // true means return handle time detail
    bool scan_detail = 11; // true means return scan cf's detail
    bool replica_read = 12;
    repeated uint64 resolved_locks = 13;
    uint64 max_execution_duration_ms = 14;

    // After a region applys to `applied_index`, we can get a
    // snapshot for the region even if the peer is follower.
    uint64 applied_index = 15;
```

**Comment by nrc** [comment]
And another question - should we implement the short value optimisation of putting short values in the lock itself?

**Comment by Connor1996** [comment]
> More things I'm unsure about given the code:
> 
> * txn heartbeat requests
> * cleanup requests (Not sure if this counts as GC)
> * MvccGetByKeyRequest and MvccGetByStartTsRequest
> * skip the constraint check in prewrites (I think this is just an optimisation, not sure).
no need, except cleanup requests(it's not only used by GC, but also for cleaning up the expired lock on primary key)

**Comment by Connor1996** [comment]
> And here is part of the Context proto, I'm guessing we don't need to support these things, but not sure:
> 
> ```
>     CommandPri priority = 6;
>     IsolationLevel isolation_level = 7;
>     bool not_fill_cache = 8;
>     bool sync_log = 9;
>     bool handle_time = 10; // true means return handle time detail
>     bool scan_detail = 11; // true means return scan cf's detail
>     bool replica_read = 12;
>     repeated uint64 resolved_locks = 13;
>     uint64 max_execution_duration_ms = 14;
> 
>     // After a region applys to `applied_index`, we can get a
>     // snapshot for the region even if the peer is follower.
>     uint64 applied_index = 15;
> ```

yes, no need to support these. Maybe keep and ignore them for now, we can delete them step by step when integrating with TinySQL.

**Comment by Connor1996** [comment]
> And another question - should we implement the short value optimisation of putting short values in the lock itself?

no need
