### ISSUE TITLE
transactions: implement request types

### ISSUE THREAD

**Issue by nrc** [pingcap-incubator/tinykv#38]
- [x] Get
- [x] Scan
- [x] Prewrite
- [x] Commit
- [x] CheckTxnStatus
- [x] Batch rollback
- [x] Resolve lock

**Comment by Connor1996** [comment]
better to implement Prewrite/Commit/Get/Scan first. I'll share a document of the proto between TinySQL with TinyKV, so we can discuss it with guys working on TinySQL to decide which part to keep and to delete.
