### ISSUE TITLE
Failed to perform `make` command under macOS with go 1.13.6

### ISSUE THREAD

**Issue by fengzixu** [pingcap-incubator/tinykv#89]
After I performed the `make` command to experience this project. I faced a problem of golang compline. The error msg as below

```
GO111MODULE=on go build  -tags codes -ldflags '-L/usr/local/opt/icu4c/lib -X "main.gitHash=`git rev-parse HEAD`" ' -o bin/tinykv-server kv/tinykv-server/main.go
# command-line-arguments
flag provided but not defined: -L/usr/local/opt/icu4c/lib
```

Then I checked the Makefile under the root directory
```
LDFLAGS             += -X "main.gitHash=`git rev-parse HEAD`" 
```
It seems like just adding the version info. The `L/usr/local/opt/icu4c/lib ` wasn't added by tinykv. So I checked the value of this env `LDFLAGS` on my host.

The answer is here
```
# echo $LDFLAGS                                                                                                                                                                                               
-L/usr/local/opt/icu4c/lib
```
`LDFLAGS` has a initial value which affected this project.

My solution is easy:

```
export LDFLAGS = ''
```

Actually, I am not sure if this initial value is necessary for tinykv. Maybe we can clear this initial value for `LDFLAGS` to avoid errors. It will be friendly for our students.

**Comment by fengzixu** [comment]
@nrc @Connor1996 Please check this issue. If it was approved, I will submit a PR to resolve it.

**Comment by Connor1996** [comment]
Thanks for your report! The `main.gitHash=`git rev-parse HEAD` is of no use now, let's just remove `-ldflags`

**Comment by fengzixu** [comment]
https://github.com/pingcap-incubator/tinykv/pull/93
