### ISSUE TITLE
Add comments for runner handler

### ISSUE THREAD

**Issue by Connor1996** [pingcap-incubator/tinykv#91]
there are some runners in raftstore to do async tasks, please add comments to describe what it is used for and how it does.

- [ ] pd_task @fengzixu https://github.com/pingcap-incubator/tinykv/blob/master/kv/tikv/raftstore/runner/pd_task.go#L38 
- [ ] raftlog_gc https://github.com/pingcap-incubator/tinykv/blob/master/kv/tikv/raftstore/runner/raftlog_gc.go
- [x] region_task @jiangyuzhao https://github.com/pingcap-incubator/tinykv/blob/master/kv/tikv/raftstore/runner/region_task.go
- [ ] split_checker @jiangyuzhao https://github.com/pingcap-incubator/tinykv/blob/master/kv/tikv/raftstore/runner/split_checker.go#L21

**Comment by fengzixu** [comment]
I will handle `add comments to pd_task`.

**Comment by jiangyuzhao** [comment]
I want to add coments to `region_task` && `split_checker`, thanks.
