### ISSUE TITLE
Make split unbatched

### ISSUE THREAD

**Issue by Connor1996** [pingcap-incubator/tinykv#96]
Remove `BatchSplitRequest` and `BatchSplitResponse` and add `SplitResponse`. https://github.com/pingcap-incubator/tinykv/blob/master/proto/proto/raft_cmdpb.proto#L86. 
Then make `OnReadySplitRegion` and `ExecBatchSplit` into an unbatched manner(only one split key).

**Comment by fengzixu** [comment]
Actually, I didn't get your point. what is OnReadyBatchSplit and ExecBatchSplit? Could you explain it ?

**Comment by fengzixu** [comment]
@Connor1996

**Comment by Connor1996** [comment]
@fengzixu Sorry, didn't explain well. Please search them in the code

**Comment by fengzixu** [comment]
@Connor1996 I see. Let met handle it.
